spring:
  datasource:
    url: jdbc:postgresql://db.docker:5432/postgres
    username: postgres
    password: postgres
    platform: POSTGRESQL
  jpa:
    hibernate.ddl-auto: validate
    properties.hibernate.temp.use_jdbc_metadata_defaults: false
  jackson:
    serialization:
      INDENT_OUTPUT: true

security:
  jwt:
    public-key: classpath:public.txt

