spring:
  datasource:
    url: jdbc:postgresql://db.docker:5432/postgres
    username: postgres
    password: postgres
    platform: POSTGRESQL
  jpa:
    hibernate.ddl-auto: validate
    properties.hibernate.temp.use_jdbc_metadata_defaults: false
#   database-platform: org.hibernate.dialect.PostgreSQL10Dialect
